apps/event_organizer/urls.py
from django.conf.urls import url
from . import views
from models import *

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signin$', views.signin, name='signin'),
    url(r'^signout$', views.signout, name='signout'),
    url(r'^register$', views.register, name='register'),
    url(r'^profile$', views.profile, name='profile'),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
    url(r'^events/new$', views.create_event, name='create_event'),
    url(r'^events/show/(?P<event_id>\d+)$', views.show_event, name='event'),
    url(r'^users/update$', views.update_user, name='update_user'),
    url(r'^users/password/update$', views.update_password, name='update_password'),
    url(r'^users/friends$', views.friends, name='friends'),
]

survey_form/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.survey.urls')),
    url(r'^session_words', include('apps.session_words.urls')),
    url(r'^amadon', include('apps.amadon.urls')),
    url(r'^user_login', include('apps.user_login.urls')),
    url(r'^user_dashboard', include('apps.user_dashboard.urls', namespace='user_dashboard')),
    url(r'^restful_users', include('apps.restful_users.urls')),
    url(r'^event_organizer', include('apps.event_organizer.urls', namespace="events")),
]

apps/event_organizer/models.py
from __future__ import unicode_literals

import re
import bcrypt

EMAIL_REGEX = '(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)'

from django.db import models

# Create your models here.

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    hashpw = models.CharField(max_length=255)
    user_level = models.IntegerField(default=1)
    friends = models.ManyToManyField('self', related_name = 'friend')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

class Address(models.Model):
    street = models.CharField(max_length=255)
    street2 = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    user = models.ForeignKey('User', on_delete = models.SET_NULL, related_name = 'address', null = True, blank = True)

class Contact(models.Model):
    full_name = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    email = models.CharField(max_length=255)

class Event(models.Model):
    created_by_user = models.ForeignKey('User', related_name = 'event', null = True, blank = True)
    indoor = models.BooleanField()
    digital = models.BooleanField()
    number_of_artists = models.SmallIntegerField()
    number_of_guests = models.SmallIntegerField()
    address = models.ForeignKey('Address', related_name = 'event')
    date = models.DateTimeField()
    start_time = models.CharField(max_length=10)
    end_time = models.CharField(max_length=10)
    contact = models.ForeignKey('Contact', related_name = 'event', null = True, blank = True)
    parking_info = models.TextField()
    border_inquiry = models.TextField()
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

apps/event_organizer/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from datetime import datetime
import bcrypt

import re

from models import *

EMAIL_REGEX = '(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)'


# Create your views here.
def index(request):
    return render(request, 'event_organizer/index.html')

def signin(request):

    # RENDER TEMPLATE
    if request.method == 'GET':
        return render(request, 'event_organizer/signin.html')

    # look for user by email
    else:
        user = User.objects.filter(email__iexact=request.POST['email'])

        # found user
        if len(user) > 0:

            hash_pw = user[0].hashpw

            # if password is correct
            if bcrypt.checkpw(request.POST['password'].encode(), hash_pw.encode()):
                messages.success(request, "Successfully logged in as {}".format(user[0].email))
                request.session['logged_in'] = True
                request.session['user_id'] = user[0].id
                return redirect(reverse('events:dashboard'))

            # Incorrect password
            else:
                messages.error(request, "Incorrect password")

        # did not find user
        else:
            messages.error(request, "did not find email in database")

        return redirect(reverse('events:signin'))

def signout(request):
    for key in request.session.keys():
        del request.session[key]
    return redirect(reverse('events:signin'))


def register(request):

    # RENDER PAGE
    if request.method == "GET":
        return render(request, 'event_organizer/register.html')

    # POST REQUEST
    else:
        errors = []
        # validate email
        if not re.match(EMAIL_REGEX, request.POST['email']):
            errors.append("Email is invalid")

        # validate password
        if len(request.POST['password']) < 8:
            errors.append('Password must be at least 8 characters in length')
        if request.POST['pw_conf'] != request.POST['password']:
            errors.append("Passwords do not match")

        #  flash error messages
        if len(errors) > 0:
            for error in errors:
                messages.error(request, error)


        # make first user an admin
        if len(User.objects.all()) < 1:
            User.objects.create(email = request.POST['email'], first_name = request.POST['first_name'], last_name = request.POST['last_name'], hashpw = bcrypt.hashpw( request.POST['password'].encode(), bcrypt.gensalt()), user_level = 9)

        # any other user is regular ( user_level =1 )
        else:
            user = User.objects.filter(email__iexact = request.POST['email'])
            if len(user) > 0:
                messages.error(request, 'User already exists in database')
                return redirect(reverse('events:register'))
            else:
                User.objects.create(email = request.POST['email'], first_name = request.POST['first_name'], last_name = request.POST['last_name'], hashpw = bcrypt.hashpw( request.POST['password'].encode(), bcrypt.gensalt()))

        messages.success(request, "Successfully created user: {}".format(request.POST['email']))
        return redirect(reverse('events:register'))

def profile(request):
    if not check_login(request):\
        return redirect(reverse('events:signin'))

    context = {
        'user' : User.objects.get(id=request.session['user_id']),
        'states' : states
    }

    # if address exists for user, pass it
    if len(User.objects.filter(id=request.session['user_id'])[0].address.values()) > 0:
        context['address'] = User.objects.filter(id=request.session['user_id'])[0].address.values()[0]

    return render(request, 'event_organizer/profile.html', context)

def update_user(request):

    # make sure required inputs are met
    email = request.POST['email']
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    # phone is optional
    phone = request.POST['phone']

    # if any part of address is filled
    # require all fields to be present
    address = {
        'street' : request.POST['street'],
        'street2' : request.POST['street2'],
        'city' : request.POST['city'],
        'state' : request.POST['state'],
        'zipcode' : request.POST['zipcode']
    }

    hasAddress = False
    for key in address:
        if address[key] != '':
            hasAddress = True

    hasErrors = False
    #  get user
    user = User.objects.get(id=request.session['user_id'])

    # check if email is different
    if user.email.lower() != email.lower():
        # if different, make sure it's not already taken
        errors = User.objects.filter(email__iexact = email)
        if len(errors):
            messages.error(request, "That email already exists")
        hasErrors = True

    # if any errors, don't create user
    if hasErrors:
        return redirect(reverse("events:profile"))

    # create user
    else:

        if hasAddress == True:

            # check if any address connected to this user
            address_obj = Address.objects.filter(user=user)

            print "address_obj:"
            print address_obj.values()
            print "length:"
            print len(address_obj)
            # it exists, update it with this data
            if len(address_obj) > 0:
                address_obj[0].street = request.POST['street']
                address_obj[0].street2 = request.POST['street2']
                address_obj[0].city = request.POST['city']
                address_obj[0].state = request.POST['state']
                address_obj[0].zipcode = request.POST['zipcode']
                address_obj[0].save()
            # it doesn't exist, so create new address
            else:
                address_obj = Address.objects.create(street = request.POST['street'], street2 = request.POST['street2'], city = address['city'], state = address['state'], zipcode = address['zipcode'])
                print "address obj:"
                print address_obj
                address_obj.user = user
                address_obj.save()
                messages.success(request,'Did not find address: creating one')
        else:
            # remove address
            user.address.remove()


        user.phone = phone
        user.save()
        messages.success(request, "Successfully updated user")
        return redirect(reverse("events:profile"))

def update_password(request):

    password = request.POST['password']
    pw_conf = request.POST['pw_conf']

    errors = False

    if len(password) < 8:
        messages.error(request, "Password must be at least 8 characters in length")
        errors = True
    if password != pw_conf:
        messages.error(request, "Passwords do not match")
        errors = True

    if errors:
        return redirect(reverse("events:profile"))
    else:
        user = User.objects.get(id=request.session['user_id'])
        user.hashpw = bcrypt.hashpw( request.POST['password'].encode(), bcrypt.gensalt() )
        user.save()
        messages.success(request, "Successfully updated password")

    return redirect(reverse("events:profile"))

def dashboard(request):
    # check if logged in
    if not check_login(request):
        return redirect(reverse('events:signin'))
    # else:
    #     return render(request, 'event_organizer/dashboard.html')
    context = {
        'events' : Event.objects.filter(created_by_user=request.session['user_id'])
    }
    return render(request, 'event_organizer/dashboard.html', context)

def create_event(request):
    if check_login(request) == False:
        return redirect(reverse('events:login'))
    else:
        context = {
            'states' : states
        }
        if request.method == "GET":
            return render(request, 'event_organizer/create_event.html', context)
        else:
            formVals = {
                'date' : request.POST['date'],
                'num_guests' : request.POST['num_guests'],
                'start_time' : request.POST['start_time'],
                'end_time' : request.POST['end_time'],
                'number_of_artists' : request.POST['number_of_artists'],
                'desc' : request.POST['desc'],
                'indoor_outdoor' : request.POST['indoor_outdoor'],
                'digital_traditional' : request.POST['digital_traditional'],
                'custom_border' : request.POST['custom_border'],
                'parking_info' : request.POST['parking_info'],
                'contact_name' : request.POST['contact_name'],
                'company' : request.POST['company'],
                'phone' : request.POST['contact_phone'],
                'email' : request.POST['contact_email'],
                'street' : request.POST['street'],
                'street2' : request.POST['street2'],
                'city' : request.POST['city'],
                'state' : request.POST['state'],
                'zipcode' : request.POST['zipcode']
            }
            print formVals


            # create client object, store as variable to reference later
            contact = Contact.objects.create(full_name = formVals['contact_name'], phone = formVals['phone'], email = formVals['email'])

            # create address object, store as variable to reference later
            address = Address.objects.create(street=formVals['street'], street2=formVals['street2'], city=formVals['city'], state=formVals['state'], zipcode=formVals['zipcode'])

            indoor = False
            digital = False
            if formVals['indoor_outdoor'] == 'indoor':
                indoor = True

            if formVals['digital_traditional'] == 'digital':
                digital = True

            # create event object and attach client and address and user
            event = Event.objects.create(
                created_by_user = User.objects.get(id=request.session['user_id']),

apps/event_organizer/templates/event_organizer/dashboard.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Event Organizer: Dashboard</title>
        <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% load static %}
        {% load time_extras %}
        <link rel="stylesheet" href="{% static 'event_organizer/css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'event_organizer/css/dashboard.css' %}">
        <script type="text/javascript" src='{% static "event_organizer/js/dashboard.js" %}'>

        </script>
    </head>
    <body>

        <!--NAV BAR-->
        <div class="nav-bar">
            <div class="inline nav-left">
                <p style='font-size:1.5em;'>Event Organizer</p>
                <a href="{% url 'events:profile' %}" style='margin-left: 10px;line-height:37px;vertical-align:top;'>Profile</p>
                <a href="{% url 'events:friends' %}" style='margin-left: 10px;line-height:37px;vertical-align:top;'>Friends</p>
            </div>
            <div class="inline nav-right">
                <a style='line-height:37px;' href='{% url "events:signout" %}'>Sign Out</a>
            </div>
        </div>

        <div class="container">
            <h1>Dashboard</h1>

            <!--MESSAGES-->
            {% if messages %}
            {% for message in messages %}
            <div class="col-xs-12">
                <center class='alert alert-{% if message.tags == "success" %}success{% else %}danger{% endif %}'>{{message}}</center>
            </div>
            {% endfor %}
            {% endif %}

            <a href='{% url "events:create_event" %}'><button class='btn btn-success'>New Event</button></a>

            <div class="events row" style='padding:20px;'>
                {% for event in events %}
                <div class="col-md-3">
                    <div class="event">
                        <h5>{{event.date | date:'F j, o'}}</h5>
                        <p>Start: <strong>{{event.start_time | hour_test}}</strong></p>
                        <p>End: <strong>{{event.end_time | hour_test}}</strong></p>
                        <p>Duration: <strong>{{event.start_time | hour_diff:event.end_time}}</strong></p>
                        <p>Description: {{event.desc}}</p>
                        <a style='margin-top:10px;' class='btn btn-sm btn-primary' href="{% url 'events:event' event_id=event.id %}">View event..</a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>

    </body>
</html>

apps/event_organizer/templates/event_organizer/friends.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Event Organizer: Friends</title>
    </head>
    <script
src="https://code.jquery.com/jquery-3.3.1.js"
integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% load static %}
    {% load time_extras %}
    <link rel="stylesheet" href="{% static 'event_organizer/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'event_organizer/css/friends.css' %}">
    <script type="text/javascript" src='{% static "event_organizer/js/utils.js" %}'></script>
    <script type="text/javascript" src='{% static "event_organizer/js/friends.js" %}'></script>

    <body>


                <!--NAV BAR-->
                <div class="nav-bar">
                    <div class="inline nav-left">
                        <p style='font-size:1.5em;'>Event Organizer</p>
                        <a href='{% url "events:dashboard" %}' style='margin-left: 10px;line-height:37px;vertical-align:top;'>Dashboard</a>
                        <a href="{% url 'events:profile' %}" style='margin-left: 10px;line-height:37px;vertical-align:top;'>Profile</p>
                    </div>
                    <div class="inline nav-right">
                        <a style='line-height:37px;' href='{% url "events:signout" %}'>Sign Out</a>
                    </div>
                </div>

                <div class="container">
                    <h1>Friends</h1>
                    <!--MESSAGES-->
                    {% if messages %}
                    {% for message in messages %}
                    <div class="col-xs-12">
                        <center class='alert alert-{% if message.tags == "success" %}success{% else %}danger{% endif %}'>{{message}}</center>
                    </div>
                    {% endfor %}
                    {% endif %}

                    <div id='flashMessage'></div>

                    <p>Search by:
                    First Name <input type="radio" name="friend_search_type" value="first_name"> |
                    Last Name <input type="radio" name="friend_search_type" value="last_name"> |
                    Email <input type="radio" name="friend_search_type" value="email">
                    </p>
                    <div class="row">
                        <div class="col-md-3">
                            <input type="text" class='form-control' name="friend_search" value="" placeholder="Friend's First Name">
                        </div>
                        <input class='btn btn-primary' type="submit" name="" value="Find Friend">
                    </div>
                </div>

    </body>
</html>

apps/event_organizer/templates/event_organizer/profile.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Event Organizer: Profile</title>
        <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'event_organizer/css/styles.css' %}">
        <script type="text/javascript" src='{% static "event_organizer/js/profile.js" %}'></script>
    </head>
    <body>

                <!--NAV BAR-->
                <div class="nav-bar">
                    <div class="inline nav-left">
                        <p style='font-size:1.5em;'>Event Organizer</p>
                        <a href="{% url 'events:dashboard' %}"><p style='margin-left: 10px;line-height:37px;vertical-align:top;'>Dashboard</p></a>
                        <a href="{% url 'events:friends' %}" style='margin-left: 10px;line-height:37px;vertical-align:top;'>Friends</p>
                    </div>
                    <div class="inline nav-right">
                        <a style='line-height:37px;' href='{% url "events:signout" %}'>Sign Out</a>
                    </div>
                </div>

                <div class="container">
                    <div style='display:inline-block;width:50%;'>
                        <h1>Profile: {{user.first_name}} {{user.last_name}}</h1>
                    </div><div style='display:inline-block;text-align:right;width:50%'>
                        <a href="{% url 'events:dashboard' %}"><button class='btn btn-primary'>Back to Dashboard</button></a>
                    </div>

                    <!--MESSAGES-->
                    {% if messages %}
                    {% for message in messages %}
                        <center style='cursor:pointer' class='alert alert-{% if message.tags == "success" %}success{% else %}danger{% endif %} row"'>{{message}}</center>
                    {% endfor %}
                    {% endif %}
                    <div class="row">
                        <div class="col-md-6">
                            <form action="{% url 'events:update_user'%}" method="post">
                                {% csrf_token %}
                                <h5>User info</h5>
                                <p style='font-size:.75em'><em>* Required</em></p>
                                <label for="email">Email*</label>
                                <input type="email" name="email" value="{{user.email}}" class='form-control' required>
                                <label for="first_name">First Name*</label>
                                <input type="text" name="first_name" value="{{user.first_name}}" class='form-control' required pattern=".{3,}" title='First name must be at least 3 characters in length'>
                                <label for="last_name">Last Name*</label>
                                <input type="text" name="last_name" value="{{user.last_name}}" class='form-control' required pattern=".{3,}" title='Last name must be at least 3 characters in length'>
                                <label for="phone">Phone Number</label>
                                <input type="tel" name="phone" value="{{user.phone}}" class='form-control' pattern='^\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})[-. )]*(\d{3})[-. ]*(\d{4})(?: *x(\d+))?\s*$' title="Example: (555) 555-5555">

                                <br>
                                <h5>Address</h5>
                                <div id='addressForm'>
                                    <label for="street1">Street Address</label>
                                    <input type="text" name="street" value="{{address.street}}" class='form-control'>
                                    <input type="text" name="street2" value="{{address.street2}}" class='form-control' style='margin-top:5px;'>
                                    <label for="city">City</label>
                                    <input type="text" name="city" value="{{address.city}}" class='form-control'>
                                    <label for="state">State</label>
                                    <select name='state' class='form-control'>
                                        <option value=''>--Select State--</option>
                                        {% for state in states %}
                                            {% if address.state == state %}
                                            <option value="{{state}}" selected>{{state}}</option>
                                            {% else %}
                                            <option value="{{state}}">{{state}}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                    <label for="zipcode">Zipcode</label>
                                    <input type="text" name="zipcode" value="{{address.zipcode}}" class='form-control'>
                                </div>
                                <br>
                                <div style='text-align:right'>
                                    <input type="submit" class='btn btn-success' name="" value="Save">
                                </div>
                            </form>

                        </div>
                        <div class="col-md-6">
                            <form action="{% url 'events:update_password' %}" method="post">
                                {% csrf_token %}
                                <h5>Update Password</h5>
                                <p><em style='font-size:.75em'>* Required</em></p>
                                <label for="password">Password</label>
                                <input type="password" class='form-control' name="password" required pattern='.{8,}' title='Password must be at least 8 characters in length'>
                                <label for="pw_conf">Confirm Password</label>
                                <input type="password" class='form-control' name="pw_conf" required pattern='.{8,}' title='Confirm Password must be at least 8 characters in length'>
                                <br>
                                <div style='text-align:right;'>
                                    <input type="submit" class="btn btn-success" value="Update Password">
                                </div>
                            </form>
                        </div>
                    </div>


                </div>

    </body>
</html>

apps/event_organizer/templates/event_organizer/register.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Event Organizer: Register</title>
        <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'event_organizer/css/styles.css' %}">
    </head>
    <body>

        <!--NAV BAR-->
        <div class="nav-bar">
            <div class="inline nav-left">
                <p style='font-size:1.5em;'>Event Organizer</p>
                <p style='margin-left: 10px;line-height:37px;vertical-align:top;'>
                    <a href='{% url "events:index" %}'>Home</a>
                </p>
            </div>
            <div class="inline nav-right">
                <a href='{% url "events:signin" %}' style='line-height:37px;'>Sign in</a>
            </div>
        </div>

        <div class="container">
            <h1>Register</h1>
            {% if messages %}
            {% for message in messages %}
            <div class="col-xs-12">
                <center class='alert alert-{% if message.tags == "success" %}success{% else %}danger{% endif %}'>{{message}}</center>
            </div>
            {% endfor %}
            {% endif %}

            <form  action="{% url 'events:register' %}" method="post">
                {% csrf_token %}
                <label for="email">Email Address:</label>
                <input type="email" class='form-control col-md-5' name="email" value="" placeholder='Email' required><br>
                <label for="first_name">First Name:</label>
                <input type="text" class='form-control col-md-5' name="first_name" value="" placeholder='First Name' required pattern='.{3,}' title='First name must be at least 3 characters in length'><br>
                <label for="last_name">Last Name:</label>
                <input type="text" class='form-control col-md-5' name="last_name" value="" placeholder='Last Name' required pattern='.{3,}' title='Last name must be at least 3 characters in length'><br>
                <label for="password">Password:</label>
                <input type="password" class='form-control col-md-5' name="password" value="" placeholder='Password' required pattern='.{8,}' title='Password must be at least 8 characters in length'><br>
                <label for="pw_conf">Password Confirm:</label>
                <input type="password" class='form-control col-md-5' name="pw_conf" value="" placeholder='Password Confirm' required pattern='.{8,}' title='Passwords must match'><br>
                <input type="submit" class='btn btn-success' value="Register">
            </form>
            <br>
            <a href="{% url 'events:signin' %}">Already have an account? Login</a>
        </div>
    </body>
</html>