apps/user_dashboard/urls.py
from django.conf.urls import url
from . import views
from models import *

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signin$', views.signin, name = 'sign_in'),
    url(r'^logoff$', views.log_off, name = 'log_off'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^dashboard$', views.dashboard, name = 'dashboard'),
    url(r'^users/edit$', views.edit, name = 'edit_user'),
    url(r'^users/new$', views.new_user, name = 'new_user'),
    url(r'^users/destroy/(?P<user_id>\d+)$', views.destroy, name = 'destroy_user'),
    url(r'^users/edit/(?P<user_id>\d+)$', views.edit_user_id, name = 'edit_user_id'),
    url(r'^users/(?P<user_id>\d+)/show$', views.show, name = 'show_user'),
    url(r'^users/update/$', views.update, name = 'update_user'),
    url(r'^users/update/(?P<user_id>\d+)$', views.update_user_id, name = 'update_user_id'),
    url(r'^users/update_password$', views.update_password, name = 'update_password'),
    url(r'^users/update_password/(?P<user_id>\d+)$', views.update_password_id, name = 'update_password_id'),
    url(r'^users/update_desc$', views.update_desc, name = 'update_desc'),
    url(r'^users/(?P<user_id>\d+)/message$', views.message, name='message'),
    url(r'^users/(?P<message_id>\d+)/comment$', views.comment, name='comment'),
]

survey_form/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.survey.urls')),
    url(r'^session_words', include('apps.session_words.urls')),
    url(r'^amadon', include('apps.amadon.urls')),
    url(r'^user_login', include('apps.user_login.urls')),
    url(r'^user_dashboard', include('apps.user_dashboard.urls', namespace='user_dashboard')),
    url(r'^restful_users', include('apps.restful_users.urls')),
    url(r'^event_organizer', include('apps.event_organizer.urls', namespace="events")),
]

apps/user_dashboard/models.py
from __future__ import unicode_literals

import re
import bcrypt

EMAIL_REGEX = '(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)'


from django.db import models

# Create your models here.
class UserManager(models.Manager):
    def basic_validator(self, postData):
        print "postData:"
        print postData
        errors = {}
        if not re.match(EMAIL_REGEX, postData['email']):
            errors['email'] = "Email is invalid"
        if len(postData['first_name']) < 3:
            errors['first_name'] = "First name must be at least 3 characters"
        if len(postData['first_name']) < 3:
            errors['last_name'] = "Last name must be at least 3 characters"
        if len(postData['password']) < 8:
            errors['password'] = "Password must be at least 3 characters"
        if postData['password'] != postData['pw_conf']:
            errors['pw_conf'] = "Passwords don't match!"
        return errors

    def user_exist_check(self, postData):
        errors = {}
        user = User.objects.filter(email__iexact = postData['email'])
        if len(user):
            errors['email'] = "That email has already been taken"
        print "Email is not taken"
        return errors

    def user_add(self, postData):
        users = User.objects.all()
        if len(users) < 1:
            print "no users yet, make this user an admin"
            user = User.objects.create(first_name = postData['first_name'], last_name = postData['last_name'], email = postData['email'], hash_pw = bcrypt.hashpw( postData['password'].encode(), bcrypt.gensalt()), user_level = 9)
            return
        else:
            user = User.objects.create(first_name = postData['first_name'], last_name = postData['last_name'], email = postData['email'], hash_pw = bcrypt.hashpw( postData['password'].encode(), bcrypt.gensalt()), user_level = 0)
            return user

    def get_user_by_email(self, email):
        user = User.objects.filter(email__iexact=email)
        print "in get user by email"
        print user
        print "lenght of user:"
        print len(user)
        if len(user) < 1:
            return False
        else:
            return True

class User(models.Model):
    first_name = models.CharField(max_length = 255)
    last_name = models.CharField(max_length = 255)
    email = models.CharField(max_length = 255)
    hash_pw = models.CharField(max_length = 255)
    user_level = models.IntegerField()
    desc = models.TextField(default='')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

class MessageManager(models.Manager):
    def validate_message(self, postData):
        print "validating message"
        return


class Message(models.Model):
    message = models.TextField(default='')
    message_by = models.ForeignKey(User, related_name = 'message_by')
    message_to = models.ForeignKey(User, related_name = 'message_to')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = MessageManager()

class CommentManager(models.Manager):
    def validate_comment(self, postData):
        print "validating comment"
        return

class Comment(models.Model):
    comment = models.TextField(default='')
    comment_by = models.ForeignKey(User, related_name = 'comment_by')
    message = models.ForeignKey(Message, related_name = 'comment')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = CommentManager()

apps/user_dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from datetime import datetime
import bcrypt

import re

EMAIL_REGEX = '(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)'

from models import *
# Create your views here.
def index(request):
    return render(request, 'user_dashboard/index.html')

def signin(request):
    if request.method == 'GET':
        context = {
            'messages' : messages.get_messages(request)
        }
        return render(request, 'user_dashboard/signin.html', context)
    else:
        print "attempting to sign in"
        print request.POST['email']
        print request.POST['password']
        user = User.objects.get_user_by_email(request.POST['email'])
        print "user after get:"
        print user
        if user == False:
            messages.error(request, "User is not in database")
            return redirect(reverse('user_dashboard:sign_in'))
        else:
            user = User.objects.filter(email__iexact=request.POST['email'])
            hash_pw = user[0].hash_pw
            password = request.POST['password']
            if bcrypt.checkpw(password.encode(), hash_pw.encode()):
                messages.success(request, "Successfully logged in")
                request.session['logged_in'] = True
                request.session['user_id'] = user[0].id
                request.session['user_level'] = user[0].user_level
                return redirect(reverse('user_dashboard:dashboard'))
            else:
                messages.error(request, "Incorrect username or password")
                request.session['logged_in'] = False
            return redirect(reverse('user_dashboard:sign_in'))

def log_off(request):
    for key in request.session.keys():
        del request.session[key]
    return redirect(reverse('user_dashboard:sign_in'))


def register(request):
    if request.method == "GET":
        context = {
            'messages' : messages.get_messages(request)
        }
        return render(request, 'user_dashboard/register.html', context)
    else:
        errors = User.objects.basic_validator(request.POST)
        if len(errors):
            messages.error(request, "There were errors validating input")
            print errors
            return redirect(reverse('user_dashboard:register'))
        errors = User.objects.user_exist_check(request.POST)
        if len(errors):
            for error in errors:
                messages.error(request, "That email is already taken")
            print errors
            return redirect(reverse('user_dashboard:register'))
        else:
            print "No errors validating"
            user = User.objects.user_add(request.POST)
            messages.success(request, "Successfully registered user")
            print user
            return redirect(reverse('user_dashboard:sign_in'))

def dashboard(request):
    if 'logged_in' not in request.session:
        messages.error(request, 'Not logged in')
        return redirect(reverse('user_dashboard:sign_in'))
    context = {
        'users' : User.objects.all()
    }
    return render(request, 'user_dashboard/dashboard.html', context)

def new_user(request):
    if request.method == "GET":
        return render(request, 'user_dashboard/new_user.html')
    else:
        errors = User.objects.basic_validator(request.POST)
        if len(errors):
            messages.error(request, "There were errors validating input")
            print errors
            return redirect(reverse('user_dashboard:new_user'))
        errors = User.objects.user_exist_check(request.POST)
        if len(errors):
            for error in errors:
                messages.error(request, "That email is already taken")
            print errors
            return redirect(reverse('user_dashboard:new_user'))
        else:
            print "No errors validating"
            user = User.objects.user_add(request.POST)
            messages.success(request, "Successfully registered user")
            print user
            return redirect(reverse('user_dashboard:new_user'))

def edit(request):
    if 'logged_in' not in request.session:
        messages.error(request, 'Not logged in')
        return redirect(reverse('user_dashboard:sign_in'))
    context = {
        'user' : User.objects.get(id=request.session['user_id'])
    }
    return render(request, 'user_dashboard/edit.html', context)

def edit_user_id(request, user_id):
    if 'logged_in' not in request.session:
        messages.error(request, 'Not logged in')
        return redirect(reverse('user_dashboard:sign_in'))
    if request.session['user_level'] != 9:
        messages.error(request, 'You do not have access to this page')
        return redirect(reverse('user_dashboard:dashboard'))

    context = {
        'user' : User.objects.get(id=user_id)
    }
    return render(request, 'user_dashboard/edit_user_id.html', context)

def destroy(request,user_id):
    print 'in destroy user'
    user = User.objects.get(id=user_id).delete()
    messages.success(request, 'Successfully deleted user')
    return redirect(reverse('user_dashboard:dashboard'))

def update(request):
    print "in update"
    user = User.objects.get(id=request.session['user_id'])
    print "got user:"
    email = request.POST['email']
    fn = request.POST['first_name']
    ln = request.POST['last_name']

    # validate post data
    errors = []
    if not re.match(EMAIL_REGEX, email):
        errors.append('Email is invalid')
    if len(fn) < 3 or len(ln) < 3:
        errors.append("First and Last name must be at least 3 characters in length")
    if len(errors):
        for error in errors:
            messages.error(request, error)
        return redirect(reverse('user_dashboard:edit_user'))

    if user.email.lower() != email.lower():
        print "attempting to change email"
        errors = User.objects.user_exist_check(request.POST)
        if len(errors) > 0:
            messages.error(request, "That email is already taken")
            return redirect(reverse('user_dashboard:edit_user'))
        else:
            print "That email is not taken"
            user.email = email
            user.first_name = fn
            user.last_name = ln
            user.save()
            messages.success(request, 'Successfully edited user information')
            return redirect(reverse('user_dashboard:edit_user'))
    else:
        user.email = email
        user.first_name = fn
        user.last_name = ln
        user.save()
    messages.success(request, 'Successfully edited user information')
    return redirect(reverse('user_dashboard:edit_user'))

def update_user_id(request, user_id):
    print "in update_user_id"

    user = User.objects.get(id=user_id)

    if user.email.lower() != request.POST['email'].lower():
        errors = User.objects.filter(email__iexact=request.POST['email'])
        if len(errors):
            messages.error(request, "Found another user with that email")
        else:
            user.email = request.POST['email']
            user.first_name = request.POST['first_name']
            user.last_name = request.POST['last_name']
            user.save()
            messages.success(request, "Successfully changed user's info!")
    else:
        user.email = request.POST['email']
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.save()
        messages.success(request, "Successfully changed user's info!")
    return redirect(reverse('user_dashboard:edit_user_id', kwargs={'user_id':user_id}))

def update_password(request):
    errors = []
    if len(request.POST['password']) < 8:
        errors.append("Password must be at least 8 characters")
    if request.POST['password'] != request.POST['pw_conf']:
        errors.append("Passwords do not match")

    if len(errors) > 0:
        for error in errors:
            messages.error(request, error)
        return redirect(reverse('user_dashboard:edit_user'))

    user = User.objects.get(id=request.session['user_id'])
    user.hash_pw = bcrypt.hashpw( request.POST['password'].encode(), bcrypt.gensalt())
    user.save()
    messages.success(request, "Successfully updated password")
    return redirect(reverse('user_dashboard:edit_user'))

def update_password_id(request, user_id):
    print "in update_password_id"
    errors = []
    if len(request.POST['password']) < 8:
        errors.append("Password must be at least 8 characters")
    if request.POST['password'] != request.POST['pw_conf']:
        errors.append("Passwords do not match")

    if len(errors) > 0:
        for error in errors:
            messages.error(request, error)
        return redirect(reverse('user_dashboard:edit_user_id', kwargs={'user_id':user_id}))

    user = User.objects.get(id=user_id)
    user.hash_pw = bcrypt.hashpw( request.POST['password'].encode(), bcrypt.gensalt())
    user.save()
    messages.success(request, "Successfully updated password")
    return redirect(reverse('user_dashboard:edit_user_id', kwargs={'user_id':user_id}))

def update_desc(request):
    user = User.objects.get(id=request.session['user_id'])
    print "got user:" + str(user.first_name)
    print "user desc:" + str(user.desc)
    user.desc = request.POST['desc']
    user.save()
    messages.success(request, "Successfully updated user description")
    return redirect(reverse('user_dashboard:edit_user'))

def show(request, user_id):

    context = {
        'user' : User.objects.get(id=user_id),
        'now' : datetime.now(),
        'user_messages' : Message.objects.filter(message_to=user_id),
        'messages' : messages.get_messages(request),
        'comments' : Comment.objects.filter(id__in = Message.objects.filter(message_to=user_id).values('comment'))
    }
    return render(request, 'user_dashboard/user.html', context)

def message(request, user_id):

    user = User.objects.get(id=user_id)

apps/user_dashboard/templates/user_dashboard/dashboard.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Dashboard</title>
        <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'user_dashboard/css/styles.css' %}">
    </head>
    <body>
        <!--NAV BAR-->
        <div class="nav-bar">
            <div class="inline nav-left">
                <p style='font-size:1.5em;'>User Dashboard</p>
                <p><a href='{% url "user_dashboard:dashboard" %}'>Dashboard</a></p>
                <p><a href="{% url 'user_dashboard:edit_user' %}">Profile</a></p>
            </div>
            <div class="inline nav-right">
                <a href='{% url "user_dashboard:log_off" %}'style='line-height:37px;'>Log off</a>
            </div>
        </div>

        <div class="container">
            <h1>Manage Users</h1>

            <!--MESSAGES-->
            {% if messages %}
            {% for message in messages %}
            <div class="col-xs-12">
                <center>{{message}}</center>
            </div>
            {% endfor %}
            {% endif %}

            <!--ADMIN BUTTON-->
            {% if request.session.user_level == 9 %}
            <a href='{% url "user_dashboard:new_user" %}'><button type="button" name="button" class='btn btn-primary' style='float:right;'>Add User</button></a>
            {% endif %}

            <table class='table table-striped' style='margin-top:80px;'>
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Date Created</th>
                        <th>User level</th>
                        {% if request.session.user_level == 9 %}
                        <th>Actions</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <th>{{user.id}}</th>
                        <th><a href='{% url "user_dashboard:show_user" user_id=user.id %}'>{{user.first_name}} {{user.last_name}}</a></th>
                        <th>{{user.email}}</th>
                        <th>{{user.created_at}}</th>
                        <th>
                            {% if user.user_level == 9 %}
                            Admin
                            {% else %}
                            Normal
                            {% endif %}
                        </th>
                        {% if request.session.user_level == 9 %}
                        <th><a href="{% url 'user_dashboard:edit_user_id' user_id=user.id %}">Edit</a> <a href="{% url 'user_dashboard:destroy_user' user_id=user.id %}">Remove</a></th>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>

    </body>
</html>

apps/user_dashboard/templates/user_dashboard/edit.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Edit User</title>
        <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'user_dashboard/css/styles.css' %}">
    </head>
    <body>
        <!--NAV BAR-->
        <div class="nav-bar">
            <div class="inline nav-left">
                <p style='font-size:1.5em;'>User Dashboard</p>
                <p><a href='{% url "user_dashboard:dashboard" %}'>Dashboard</a></p>
                <p><a href="#">Profile</a></p>
            </div>
            <div class="inline nav-right">
                <a href='{% url "user_dashboard:log_off" %}'style='line-height:37px;'>Log off</a>
            </div>
        </div>

        <div class="container">
            <h1>Edit Profile</h1>

            <!--MESSAGES-->
            {% if messages %}
            {% for message in messages %}
            <div class="col-xs-12">
                <center>{{message}}</center>
            </div>
            {% endfor %}
            {% endif %}

            <!-- CONTENT -->
            <div class="row">

                <!-- EDIT INFO-->
                <div class="col-md-6">
                    <h2>Edit Information</h2>
                    <form class="" action="{% url 'user_dashboard:update_user' %}" method="post" style='padding:0 30px;'>
                        {% csrf_token %}
                        <label for="email">Email Address:</label>
                        <input type="email" class='form-control' name="email" value="{{user.email}}" required>
                        <label for="first_name">First Name:</label>
                        <input type="text" class='form-control' name="first_name" value="{{user.first_name}}" required pattern=".{3,}" title='First name must be at least 3 characters in length'>
                        <label for="last_name">Last Name:</label>
                        <input type="text" class='form-control' name="last_name" value="{{user.last_name}}" required pattern=".{3,}" title='Last name must be at least 3 characters in length'>
                        <br>
                        <input type="submit" class='btn btn-success' value="Save" style='float:right'>
                    </form>
                </div>

                <!-- EDIT PASSWORD -->
                <div class="col-md-6">
                    <h2>Change Password</h2>
                    <form action="{% url 'user_dashboard:update_password' %}" method="post" style='padding:0 30px;'>
                        {% csrf_token %}
                        <label for="password">Password</label>
                        <input type="password" name="password" class='form-control' value="" pattern='.{8,0}' required>
                        <label for="pw_conf">Confirm Password</label>
                        <input type="password" name="pw_conf" class='form-control' value="" pattern='.{8,0}' required>
                        <br>
                        <input type="submit" class='btn btn-success' value="Update password" style='float:right'>
                    </form>
                </div>

                <div style='margin-top:20px;' class='col-md-12'>
                    <h2>Edit Description</h2>
                    <div class="row">
                        <form action="{% url 'user_dashboard:update_desc' %}" method="post" class='col-md-12'>
                            {% csrf_token %}
                            <label for="desc">Description</label>
                            <textarea name="desc" style='height:100px;'class='form-control ' >{{user.desc}}</textarea>
                            <br>
                            <input type="submit" class='btn btn-success' value="Edit Description" style='float:right;'>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </body>
</html>

apps/user_dashboard/templates/user_dashboard/edit_user_id.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Edit User</title>
        <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'user_dashboard/css/styles.css' %}">
    </head>
    <body>

        <!--NAV BAR-->
        <div class="nav-bar">
            <div class="inline nav-left">
                <p style='font-size:1.5em;'>User Dashboard</p>
                <p><a href='{% url "user_dashboard:dashboard" %}'>Dashboard</a></p>
                <p><a href="#">Profile</a></p>
            </div>
            <div class="inline nav-right">
                <a href='{% url "user_dashboard:log_off" %}'style='line-height:37px;'>Log off</a>
            </div>
        </div>

        <div class="container">
            <h1>Edit user {{user.first_name}} {{user.last_name}}</h1>

            <!--MESSAGES-->
            {% if messages %}
            {% for message in messages %}
            <div class="col-xs-12">
                <center>{{message}}</center>
            </div>
            {% endfor %}
            {% endif %}

            <div style='text-align:right'>
                <a href='{% url "user_dashboard:dashboard" %}'><button class='btn btn-primary'>Back to Dashboard</button></a>
            </div>
            <!-- CONTENT -->
            <div class="row">

                <!-- EDIT INFO-->
                <div class="col-md-6">
                    <h2>Edit Information</h2>
                    <form action="{% url 'user_dashboard:update_user_id' user_id=user.id %}" method="post" style='padding:0 30px;'>
                        {% csrf_token %}
                        <label for="email">Email Address:</label>
                        <input type="email" class='form-control' name="email" value="{{user.email}}" required>
                        <label for="first_name">First Name:</label>
                        <input type="text" class='form-control' name="first_name" value="{{user.first_name}}" required pattern=".{3,}" title='First name must be at least 3 characters in length'>
                        <label for="last_name">Last Name:</label>
                        <input type="text" class='form-control' name="last_name" value="{{user.last_name}}" required pattern=".{3,}" title='Last name must be at least 3 characters in length'>
                        <br>
                        <input type="submit" class='btn btn-success' value="Save" style='float:right'>
                    </form>
                </div>

                <!-- EDIT PASSWORD -->
                <div class="col-md-6">
                    <h2>Change Password</h2>
                    <form action="{% url 'user_dashboard:update_password_id' user_id=user.id %}" method="post" style='padding:0 30px;'>
                        {% csrf_token %}
                        <label for="password">Password</label>
                        <input type="password" name="password" class='form-control' value="" pattern='.{8,0}' required>
                        <label for="pw_conf">Confirm Password</label>
                        <input type="password" name="pw_conf" class='form-control' value="" pattern='.{8,0}' required>
                        <br>
                        <input type="submit" class='btn btn-success' value="Update password" style='float:right'>
                    </form>
                </div>


            </div>
        </div>

    </body>
</html>

apps/user_dashboard/templates/user_dashboard/new_user.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>New User</title>
        <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'user_dashboard/css/styles.css' %}">
    </head>
    <body>

        <!--NAV BAR-->
        <div class="nav-bar">
            <div class="inline nav-left">
                <p style='font-size:1.5em;'>User Dashboard</p>
                <p><a href='{% url "user_dashboard:dashboard" %}'>Dashboard</a></p>
                <p><a href="#">Profile</a></p>
            </div>
            <div class="inline nav-right">
                <a href='{% url "user_dashboard:log_off" %}'style='line-height:37px;'>Log off</a>
            </div>
        </div>

        <div class="container">
            <h1>New User</h1>

            <!--MESSAGES-->
            {% if messages %}
            {% for message in messages %}
            <div class="col-xs-12">
                <center>{{message}}</center>
            </div>
            {% endfor %}
            {% endif %}

            <div style='text-align:right'>
                <a href='{% url "user_dashboard:dashboard" %}'<button class='btn btn-primary'>Back to Dashboard</button></a>
            </div>

            <form action='{% url "user_dashboard:new_user" %}' method='post' class="col-md-4" >
                {% csrf_token %}
                <label for="email">Email Address:</label>
                <input type="email" name="email" class='form-control' value="" required>
                <label for="first_name">First Name</label>
                <input type="text" name="first_name" class='form-control' value="" pattern=".{3,}" title='First name must be at least 3 characters in length'>
                <label for="last_name">Last Name</label>
                <input type="text" name="last_name" class='form-control' value="" pattern=".{3,}" title='Last name must be at least 3 characters in length'>
                <label for="password">Password</label>
                <input type="password" name="password" class='form-control' value="" pattern=".{8,}" title='Password must be at least 8 characters in length'>
                <label for="pw_conf">Confirm Password</label>
                <input type="password" name="pw_conf" class='form-control' value="" pattern=".{8,}" title='Confirm password must be at least 8 characters in length'>
                <br>
                <input type="submit" class='btn btn-success' value="Add User">
            </form>

        </div>

    </body>
</html>